### PR TITLE
Add ability to use Autofac parameters for WCF service resolution.

### PR DESCRIPTION
**Pull request by lepberg**

### CODE REVIEW

**Comment by tillig** [comment]
Hello! Thanks for the PR. Unfortunately, the whole file appears as changed. This usually happens when the line endings get switched. Is there a way to resubmit so we can actually see what changed?

**Comment by lepberg** [comment]
Hello! Sure, I'll do it.

**Comment by lepberg** [comment]
Something strange happens here. The git plug-in of Visual Studio displays appropriate file diff, but `git diff` command says that the whole file is changed and marks the BOM bytes.

a8942148_vsgit
a8942148_gitbash

I tried to explicitly specify EOF, change my `autocrlf` settings, but nothing has helped.

**Comment by lepberg** [comment]
I've created a new [pull request](https://github.com/autofac/Autofac.Wcf/pull/6) to fix related EoF problem.

**Comment by tillig** [comment]
Pulled the EoF request and caught a couple more files that had the same problem. Thanks for the patience and the help!

I think if you can resolve the conflicts this looks like an easy enough change and fairly valuable. Thanks!

**Comment by lepberg** [comment]
No problem.
I've just noticed the misspelling in commit "Normalize EoF." that should be "Normalize EoL" of course :(

**Comment by lepberg** [comment]
Is there any way to restart appveyor build? I've got no idea why it fails.

**Comment by alexmg** [comment]
Looks like its a NuGet issue.

https://github.com/NuGet/Home/issues/2648

From the NuSpec reference:

The following table lists attributes of the frameworkAssembly element.

**assemblyName** Required. The fully qualified assembly name.
**targetFramework** Optional. If specified, the specific target framework that this reference applies to. For example, if reference only applies to .NET 4, then the value should be "net40". If the reference applies to _all_ frameworks, then omit this attribute.

I tested this was the issue by successfully packing with the `targetFramework` attribute set on the `frameworkAssembly` element. I would prefer to leave the `targetFramework` blank so maybe we just wait for 3.4.4 of NuGet to fix this. We might also have to wait for AppVeyor to start using this version if they don't automatically just pick up the latest released version.

If you can write some passing unit tests in the `ServiceHostExtensionsFixture` we could pull this in ready for when the new version of NuGet is available. There isn't any obvious issues that I can see.

https://github.com/autofac/Autofac.Wcf/blob/develop/test/Autofac.Integration.Wcf.Test/ServiceHostExtensionsFixture.cs

**Comment by lepberg** [comment]
Thanks for explaining the AppVeyor build failure.

**Comment by tillig** [comment]
I did a manual merge of this [here](https://github.com/autofac/Autofac.Wcf/commit/cc4d184c582737af3e08ff2e3cc374f5f2efd551).

**Pull request closed without merging**
